//package com.imooc.dianping.dal;
//
//import com.imooc.dianping.model.RecommendDO;
//
//public interface RecommendDOMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table recommend
//     *
//     * @mbg.generated Mon Nov 21 18:32:10 CST 2022
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table recommend
//     *
//     * @mbg.generated Mon Nov 21 18:32:10 CST 2022
//     */
//    int insert(RecommendDO record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table recommend
//     *
//     * @mbg.generated Mon Nov 21 18:32:10 CST 2022
//     */
//    int insertSelective(RecommendDO record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table recommend
//     *
//     * @mbg.generated Mon Nov 21 18:32:10 CST 2022
//     */
//    RecommendDO selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table recommend
//     *
//     * @mbg.generated Mon Nov 21 18:32:10 CST 2022
//     */
//    int updateByPrimaryKeySelective(RecommendDO record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table recommend
//     *
//     * @mbg.generated Mon Nov 21 18:32:10 CST 2022
//     */
//    int updateByPrimaryKey(RecommendDO record);
//}